# words.py
import random

CATEGORIES = {
    "Фрукты": [
        "яблоко",
        "банан",
        "апельсин",
        "груша",
        "слива",
        "вишня",
        "черешня",
        "персик",
        "абрикос",
        "гранат",
        "ананас",
        "манго",
        "киви",
        "маракуйя",
        "папайя",
        "фейхоа",
        "гуава",
        "айва",
    ],
    "Ягоды": [
        "рябина",
        "смородина",
        "крыжовник",
        "черника",
        "брусника",
        "клюква",
        "малина",
        "ежевика",
        "земляника",
        "клубника",
    ],
    "Овощи": [
        "картофель",
        "морковь",
        "свекла",
        "репа",
        "редис",
        "огурец",
        "томат",
        "перец",
        "баклажан",
        "кабачок",
    ],
    "Животные": [
        "собака",
        "кошка",
        "лошадь",
        "корова",
        "свинья",
        "овца",
        "коза",
        "курица",
        "гусь",
        "утка",
    ],
    "Города": [
        "Москва",
        "Санкт-Петербург",
        "Казань",
        "Новосибирск",
        "Екатеринбург",
        "Нижний Новгород",
        "Ростов-на-Дону",
        "Красноярск",
        "Пермь",
        "Воронеж",
    ],
    "Fruits": [
        "apple",
        "banana",
        "orange",
        "pear",
        "plum",
        "cherry",
        "apricot",
        "peach",
        "grape",
        "pineapple",
        "mango",
        "kiwi",
        "passionfruit",
        "papaya",
        "feijoa",
        "guava",
        "quince",
    ],
    "Berries": [
        "rowan",
        "currant",
        "gooseberry",
        "blueberry",
        "cranberry",
        "lingonberry",
        "raspberry",
        "blackberry",
        "strawberry ",
        "strawberry",
    ],
    "Vegetables": [
        "potato",
        "carrot",
        "beet",
        "turnip",
        "radish",
        "cucumber",
        "tomato",
        "pepper",
        "eggplant",
        "zucchini",
    ],
    "Animals": [
        "dog",
        "cat",
        "horse",
        "cow",
        "pig",
        "sheep",
        "goat",
        "chicken",
        "goose",
        "duck",
    ],
    "Cities": [
        "Moscow",
        "Saint Petersburg",
        "Kazan",
        "Novosibirsk",
        "Yekaterinburg",
        "Nizhny Novgorod",
        "Rostov-on-Don",
        "Krasnoyarsk",
        "Perm",
        "Voronezh",
    ],
}

def get_random_word(category):

    if category in CATEGORIES:

        return random.choice(CATEGORIES[category])

    else:

        return None